// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colors': string;
  'dash': string;
  'loadderContainer': string;
  'path': string;
  'rotator': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
